extern void c_levelpool_physics(float *dt,
                              float *qi0,
                              float *qi1,
                              float *ql,
                              float *ar,
                              float *we,
                              float *maxh,
                              float *wc,
                              float *wl,
                              float *dl,
                              float *oe,
                              float *oc,
                              float *oa,
                              float *H0,
                              float *H1,
                              float *qo1);
