# Organization outline for t-route V4 configuration files:

#--------------------------------------------------------------------------------
log_parameters:
    #----------
    showtiming:
    log_level :
#--------------------------------------------------------------------------------
bmi_parameters:
    #----------
    flowpath_columns:
    attributes_columns:
    waterbody_columns:
    network_columns:
#--------------------------------------------------------------------------------
network_topology_parameters:
    #----------
    supernetwork_parameters:
        #----------
        title_string:
        geo_file_path:
        network_type:
        mask_file_path:
        mask_layer_string:
        mask_driver_string:
        mask_key:
        columns:
            #----------
            key:
            downstream:
            dx:
            n:
            ncc:
            s0:
            bw:
            waterbody:
            tw:
            twcc:
            alt:
            musk:
            musx:
            cs:
            gages:
        synthetic_wb_segments:
        synthetic_wb_id_offset:
        duplicate_wb_segments:
        terminal_code:
        driver_string:
        layer_string:
    waterbody_parameters:
        #----------
        break_network_at_waterbodies:
        level_pool:
            #----------
            level_pool_waterbody_parameter_file_path:
            level_pool_waterbody_id:
        waterbody_null_code:
    preprocessing_parameters:
        #----------
        preprocess_only:
        preprocess_output_folder:
        preprocess_output_filename:
        use_preprocessed_data:
        preprocess_source_file:        
#--------------------------------------------------------------------------------
compute_parameters:
    #----------
    parallel_compute_method:
    compute_kernel:
    assume_short_ts:
    subnetwork_target_size:
    cpu_pool:
    return_courant:
    restart_parameters:
        #----------
        start_datetime:
        lite_channel_restart_file:
        lite_waterbody_restart_file:
        wrf_hydro_channel_restart_file:
        wrf_hydro_channel_ID_crosswalk_file:
        wrf_hydro_channel_ID_crosswalk_file_field_name:
        wrf_hydro_channel_restart_upstream_flow_field_name:
        wrf_hydro_channel_restart_downstream_flow_field_name:
        wrf_hydro_channel_restart_depth_flow_field_name:
        wrf_hydro_waterbody_restart_file:
        wrf_hydro_waterbody_ID_crosswalk_file:
        wrf_hydro_waterbody_ID_crosswalk_file_field_name:
        wrf_hydro_waterbody_crosswalk_filter_file:
        wrf_hydro_waterbody_crosswalk_filter_file_field_name:
        hyfeature_channel_restart_file:
    hybrid_parameters:
        #----------
        run_hybrid_routing:
        diffusive_domain:
        use_natl_xsections:
        topobathy_domain:
        run_refactored_network:
        refactored_domain:
        refactored_topobathy_domain:
        coastal_boundary_domain:
    forcing_parameters:
        #----------
        qts_subdivisions:
        dt:
        qlat_input_folder:
        nts:
        max_loop_size:
        qlat_file_index_col:
        qlat_file_value_col:
        qlat_file_gw_bucket_flux_col:
        qlat_file_terrain_runoff_col:
        qlat_file_pattern_filter:
        qlat_forcing_sets:
            #----------
            nts:
                #----------
                qlat_files:
        binary_nexus_file_folder:
        coastal_boundary_input_file:
    data_assimilation_parameters:
        #----------
        usgs_timeslices_folder:
        usace_timeslices_folder:
        timeslice_lookback_hours:
        interpolation_limit_min:
        wrf_hydro_lastobs_lead_time_relative_to_simulation_start_time:
        wrf_lastobs_type:
        streamflow_da:
            #----------
            treamflow_nudging:
            gage_segID_crosswalk_file:
            crosswalk_gage_field:
            crosswalk_segID_field:
            lastobs_file:
            lastobs_output_folder:
            diffusive_streamflow_nudging:
        reservoir_da:
            #----------
            reservoir_persistence_da:
                #----------
                reservoir_persistence_usgs:
                reservoir_persistence_usace:
                crosswalk_usgs_gage_field:
                crosswalk_usace_gage_field:
                crosswalk_usgs_lakeID_field:
                crosswalk_usace_lakeID_field:
            reservoir_rfc_da:
                #----------
                reservoir_rfc_forecasts:
                reservoir_rfc_forecasts_time_series_path:
                reservoir_rfc_forecasts_lookback_hours:
                reservoir_rfc_forecasts_offset_hours:
                reservoir_rfc_forecast_persist_days:
            reservoir_parameter_file:
        qc_threshold:
#--------------------------------------------------------------------------------
output_parameters:
    #----------
    chanobs_output:
        #----------
        chanobs_output_directory:
        chanobs_filepath:
    csv_output:
        #----------
        csv_output_folder:
        csv_output_segments:
    chrtout_output:
        #----------
        wrf_hydro_channel_output_source_folder:
    lite_restart:
        #----------
        lite_restart_output_directory:
    hydro_rst_output:
        #----------
        wrf_hydro_restart_dir:
        wrf_hydro_channel_restart_pattern_filter:
        wrf_hydro_channel_restart_source_directory:
        wrf_hydro_channel_output_source_folder:
    wrf_hydro_parity_check:
        #----------
        parity_check_input_folder:
        parity_check_file_index_col:
        parity_check_file_value_col:
        parity_check_compare_node:
        parity_check_compare_file_sets:
            #----------
            validation_files:
    lakeout_output:
    test_output: