extern void c_muskingcungenwm(float *dt,
                              float *qup,
                              float *quc,
                              float *qdp,
                              float *ql,
                              float *dx,
                              float *bw,
                              float *tw,
                              float *twcc,
                              float *n,
                              float *ncc,
                              float *cs,
                              float *s0,
                              float *velp,
                              float *depthp,
                              float *qdc,
                              float *velc,
                              float *depthc,
                              float *ck,
                              float *cn,
                              float *X);

extern void c_reachcompute(float *dt,
                            int *nseg,
                            int * nts,
                            float *qup_top,
                            float *quc_top,
                            float *qdp_rch,
                            float *ql_rch,
                            float *dx_rch,
                            float *bw_rch,
                            float *tw_rch,
                            float *twcc_rch,
                            float *n_rch,
                            float *ncc_rch,
                            float *cs_rch,
                            float *s0_rch,
                            float *velp_rch,
                            float *depthp_rch,
                            float *qdc_rch,
                            float *velc_rch,
                            float *depthc_rch,
                            float *ck_rch,
                            float *cn_rch,
                            float *X_rch);

