extern void c_muskingcungenwm(float *dt,
                              float *qup,
                              float *quc,
                              float *qdp,
                              float *ql,
                              float *dx,
                              float *bw,
                              float *tw,
                              float *twcc,
                              float *n,
                              float *ncc,
                              float *cs,
                              float *s0,
                              float *velp,
                              float *depthp,
                              float *qdc,
                              float *velc,
                              float *depthc,
                              float *ck,
                              float *cn,
                              float *X);

