extern void c_uniflowtzlt(int* mxncomp_g, 
		          int* nrch_g, 
                          double* bo_ar_g, 
                          double* traps_ar_g, 
                          double* tw_ar_g, 
                          double* twcc_ar_g, 
                          double* mann_ar_g, 
                          double* manncc_ar_g, 
                          double* so_ar_g, 
                          int* nhincr_m_g, 
                          int* nhincr_f_g, 
                          double* ufhlt_m_g, 
                          double* ufqlt_m_g, 
                          double* ufhlt_f_g, 
                          double* ufqlt_f_g, 
                          int* frnw_col, 
                          double* dfrnw_g, 
                          double* timesdepth_g);
